name: Book API CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set Up SSH Key
        env:
          AZURE_SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_KEY" > ~/.ssh/azure_ssh_key.pem
          chmod 600 ~/.ssh/azure_ssh_key.pem
          ssh-keyscan -H 128.85.131.126 >> ~/.ssh/known_hosts
          
      - name: Deploy to Azure
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@128.85.131.126 -i ~/.ssh/azure_ssh_key.pem <<EOF
            cd fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi-book.service
          EOF